name: CI
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@v0.1.4
      env:
        HOST: ${{ secrets.DEPLOY_SERVER_HOST }}
        USERNAME: ${{ secrets.DEPLOY_SERVER_USERNAME }}
        PORT: ${{ secrets.DEPLOY_SERVER_PORT }}
        KEY: ${{ secrets.DEPLOY_SERVER_KEY }}
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }}
        port: ${{ secrets.DEPLOY_SERVER_PORT }}
        username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
        key: ${{ secrets.DEPLOY_SERVER_KEY }}
        source: "."
        target: "/var/www/html/discordbot"
    - name: Deploy using ssh
      uses: appleboy/ssh-action@v0.1.4
      with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          script: |
            cd /var/www/html/discordbot
            pm2 stop all
            git pull
            npm install
            npm run start
            pm2 restart /var/www/html/discordbot/index.js

        
